// Generated by VoxelParadox.ShaderEditor node graph.
// Edit via the ShaderEditor Node Graph panel; direct edits may be overwritten.
    vec2 n_0 = uv;
    vec2 pix_1_cells = max(vec2((32.0), (32.0)), vec2(1.0));
    vec2 pix_1 = floor((n_0) * pix_1_cells) / pix_1_cells;
    vec2 n_2 = vec2(0.1, -0.1);
    float n_3 = uTime * (1.0);
    vec2 n_4 = (pix_1) + (n_2) * (n_3);
    vec2 n_5 = distortUvFbm(n_4, 0.1, n_3);
    float sn2_6_raw = snoise2((n_5) * (3.0));
    float sn2_6 = mix(sn2_6_raw, 0.5 + 0.5 * sn2_6_raw, step(0.5, 0.0));
    float sn2_7_raw = snoise2((n_5) * (5.81));
    float sn2_7 = mix(sn2_7_raw, 0.5 + 0.5 * sn2_7_raw, step(0.5, 1.0));
    vec3 n_8 = mix(vec3(sn2_6), vec3(sn2_7), 0.55);
    vec3 n_9 = vec3(0.74902, 0.160784, 1.0);
    vec3 n_10 = (n_8 * n_9);
    vec3 stone_11_alb;
    float stone_11_rough;
    {
        vec2 sp = (n_5) * (1.0);
        float strata = fbm21(vec2(sp.x * 3.4, sp.y * 1.4));
        float grain = simpleNoise2(localUv * 11.0);
        vec3 alb = (n_9) * mix(0.72, 1.15, strata);
        alb += vec3((grain - 0.5) * 0.06);
        stone_11_alb = clamp(alb, vec3(0.0), vec3(1.4));
        stone_11_rough = 0.92;
    }
    vec3 n_12 = mix(n_10, stone_11_alb, 0.18);
    float n_13 = 5.0;
    vec3 generatedAlbedo = clamp(n_12, vec3(0.0), vec3(2.0));
    float generatedRoughness = clamp(n_13, 0.0, 1.0);
    float generatedSpecular = clamp(0.1, 0.0, 2.0);
    float generatedEmissive = max(0.0, 0.0);
    return makeSample(generatedAlbedo, generatedRoughness, generatedSpecular, generatedEmissive);
