return {
  categories = {
    {
      id = "movement",
      label = "Movement",
      actions = {
        {
          id = "move_forward",
          label = "Move Forward",
          category = "movement",
          context = "gameplay",
          input_type = "keyboard",
          default_bind = "W",
        },
        {
          id = "move_backward",
          label = "Move Backward",
          category = "movement",
          context = "gameplay",
          input_type = "keyboard",
          default_bind = "S",
        },
        {
          id = "move_left",
          label = "Move Left",
          category = "movement",
          context = "gameplay",
          input_type = "keyboard",
          default_bind = "A",
        },
        {
          id = "move_right",
          label = "Move Right",
          category = "movement",
          context = "gameplay",
          input_type = "keyboard",
          default_bind = "D",
        },
        {
          id = "jump",
          label = "Jump",
          category = "movement",
          context = "gameplay",
          input_type = "keyboard",
          default_bind = "Space",
        },
        {
          id = "crouch",
          label = "Crouch",
          category = "movement",
          context = "gameplay",
          input_type = "keyboard",
          default_bind = "LeftShift",
        },
        {
          id = "run",
          label = "Run",
          category = "movement",
          context = "gameplay",
          input_type = "keyboard",
          default_bind = "LeftControl",
        },
        {
          id = "zoom",
          label = "Zoom",
          category = "movement",
          context = "gameplay",
          input_type = "keyboard",
          default_bind = "C",
        },
      },
    },
    {
      id = "interaction",
      label = "Interaction",
      actions = {
        {
          id = "break_block",
          label = "Break Block",
          category = "interaction",
          context = "gameplay",
          input_type = "mouse_button",
          default_bind = "MouseLeft",
        },
        {
          id = "place_block",
          label = "Place Block",
          category = "interaction",
          context = "gameplay",
          input_type = "mouse_button",
          default_bind = "MouseRight",
        },
        {
          id = "preview_portal",
          label = "Preview Portal",
          category = "interaction",
          context = "gameplay",
          input_type = "keyboard",
          default_bind = "V",
        },
        {
          id = "enter_portal",
          label = "Enter Portal",
          category = "interaction",
          context = "gameplay",
          input_type = "keyboard",
          default_bind = "F",
        },
        {
          id = "ascend_dimension",
          label = "Ascend Dimension",
          category = "interaction",
          context = "gameplay",
          input_type = "keyboard",
          default_bind = "R",
        },
      },
    },
    {
      id = "hotbar",
      label = "Hotbar",
      actions = {
        { id = "hotbar_slot_1", label = "Slot 1", category = "hotbar", context = "gameplay", input_type = "keyboard", default_bind = "1" },
        { id = "hotbar_slot_2", label = "Slot 2", category = "hotbar", context = "gameplay", input_type = "keyboard", default_bind = "2" },
        { id = "hotbar_slot_3", label = "Slot 3", category = "hotbar", context = "gameplay", input_type = "keyboard", default_bind = "3" },
        { id = "hotbar_slot_4", label = "Slot 4", category = "hotbar", context = "gameplay", input_type = "keyboard", default_bind = "4" },
        { id = "hotbar_slot_5", label = "Slot 5", category = "hotbar", context = "gameplay", input_type = "keyboard", default_bind = "5" },
        { id = "hotbar_slot_6", label = "Slot 6", category = "hotbar", context = "gameplay", input_type = "keyboard", default_bind = "6" },
        { id = "hotbar_slot_7", label = "Slot 7", category = "hotbar", context = "gameplay", input_type = "keyboard", default_bind = "7" },
        { id = "hotbar_slot_8", label = "Slot 8", category = "hotbar", context = "gameplay", input_type = "keyboard", default_bind = "8" },
        { id = "hotbar_slot_9", label = "Slot 9", category = "hotbar", context = "gameplay", input_type = "keyboard", default_bind = "9" },
      },
    },
    {
      id = "interface",
      label = "Interface",
      actions = {
        {
          id = "toggle_inventory",
          label = "Toggle Inventory",
          category = "interface",
          context = "ui",
          input_type = "keyboard",
          default_bind = "E",
        },
        {
          id = "toggle_pause",
          label = "Toggle Pause",
          category = "interface",
          context = "ui",
          input_type = "keyboard",
          default_bind = "Escape",
        },
        {
          id = "open_chat",
          label = "Open Chat",
          category = "interface",
          context = "ui",
          input_type = "keyboard",
          default_bind = "T",
        },
        {
          id = "toggle_portal_tracker",
          label = "Portal Tracker",
          category = "interface",
          context = "ui",
          input_type = "keyboard",
          default_bind = "P",
        },
      },
    },
    {
      id = "system",
      label = "System",
      actions = {
        {
          id = "take_screenshot",
          label = "Take Screenshot",
          category = "system",
          context = "ui",
          input_type = "keyboard",
          default_bind = "F2",
        },
        {
          id = "toggle_hud",
          label = "Toggle HUD",
          category = "system",
          context = "ui",
          input_type = "keyboard",
          default_bind = "F1",
        },
        {
          id = "toggle_fullscreen",
          label = "Toggle Fullscreen",
          category = "system",
          context = "ui",
          input_type = "keyboard",
          default_bind = "F11",
        },
      },
    },
    {
      id = "ui_navigation",
      label = "UI Navigation",
      actions = {
        {
          id = "ui_accept",
          label = "Accept",
          category = "ui_navigation",
          context = "ui_navigation",
          input_type = "keyboard",
          default_bind = "Enter",
        },
        {
          id = "ui_cancel",
          label = "Cancel",
          category = "ui_navigation",
          context = "ui_navigation",
          input_type = "keyboard",
          default_bind = "Escape",
        },
        {
          id = "ui_up",
          label = "Move Up",
          category = "ui_navigation",
          context = "ui_navigation",
          input_type = "keyboard",
          default_bind = "Up",
        },
        {
          id = "ui_down",
          label = "Move Down",
          category = "ui_navigation",
          context = "ui_navigation",
          input_type = "keyboard",
          default_bind = "Down",
        },
        {
          id = "ui_left",
          label = "Move Left",
          category = "ui_navigation",
          context = "ui_navigation",
          input_type = "keyboard",
          default_bind = "Left",
        },
        {
          id = "ui_right",
          label = "Move Right",
          category = "ui_navigation",
          context = "ui_navigation",
          input_type = "keyboard",
          default_bind = "Right",
        },
        {
          id = "ui_delete",
          label = "Delete",
          category = "ui_navigation",
          context = "ui_navigation",
          input_type = "keyboard",
          default_bind = "Delete",
        },
      },
    },
  },
}
