// Generated by VoxelParadox.ShaderEditor node graph.
// Edit via the ShaderEditor Node Graph panel; direct edits may be overwritten.
    vec3 n_0 = vec3(1.0, 0.0, 0.847059);
    vec3 n_1 = vec3(0.152941, 0.0, 0.435294);
    vec2 n_2 = localUv;
    vec2 pix_3_cells = max(vec2((32.0), (32.0)), vec2(1.0));
    vec2 pix_3 = floor((n_2) * pix_3_cells) / pix_3_cells;
    float n_4 = uTime * (1.0);
    vec2 rot_5_anchor = (vec2(0.5, 0.5));
    vec2 rot_5_delta = (pix_3) - rot_5_anchor;
    float rot_5_a = (n_4);
    float rot_5_s = sin(rot_5_a);
    float rot_5_c = cos(rot_5_a);
    vec2 rot_5 = vec2(rot_5_delta.x * rot_5_c - rot_5_delta.y * rot_5_s, rot_5_delta.x * rot_5_s + rot_5_delta.y * rot_5_c) + rot_5_anchor;
    vec2 n_6 = swirlUv(rot_5, 10.0);
    float sn2_7_raw = snoise2((n_6) * (1.0));
    float sn2_7 = mix(sn2_7_raw, 0.5 + 0.5 * sn2_7_raw, step(0.5, 0.0));
    vec3 n_8 = mix(n_0, n_1, sn2_7);
    float n_9 = 0.2;
    vec3 n_10 = (n_8 * vec3(n_9));
    vec3 generatedAlbedo = clamp(n_8, vec3(0.0), vec3(2.0));
    float generatedRoughness = clamp(0.8, 0.0, 1.0);
    float generatedSpecular = clamp(0.1, 0.0, 2.0);
    float generatedEmissive = max((n_10).x, 0.0);
    return makeSample(generatedAlbedo, generatedRoughness, generatedSpecular, generatedEmissive);
