// Generated by VoxelParadox.ShaderEditor node graph.
// Edit via the ShaderEditor Node Graph panel; direct edits may be overwritten.
    vec2 n_0 = faceUv(worldPos, faceNormal) * (1.0);
    float n_1 = uTime;
    vec2 n_2 = distortUvFbm(n_0, 0.42, n_1);
    vec4 n_3 = sampleBlockTexture(materialId, n_2);
    vec3 generatedAlbedo = clamp((n_3).xyz, vec3(0.0), vec3(2.0));
    float generatedRoughness = clamp(0.8, 0.0, 1.0);
    float generatedSpecular = clamp(0.1, 0.0, 2.0);
    float generatedEmissive = max(0.0, 0.0);
    return makeSample(generatedAlbedo, generatedRoughness, generatedSpecular, generatedEmissive);
