// Generated by VoxelParadox.ShaderEditor node graph.
// Edit via the ShaderEditor Node Graph panel; direct edits may be overwritten.
    vec2 n_0 = localUv;
    vec2 pix_1_cells = max(vec2((32.0), (32.0)), vec2(1.0));
    vec2 pix_1 = floor((n_0) * pix_1_cells) / pix_1_cells;
    float n_2 = uTime * (0.2);
    vec2 n_3 = distortUvFbm(pix_1, 0.42, n_2);
    vec4 n_4 = sampleBlockTexture(materialId, n_3);
    vec3 generatedAlbedo = clamp((n_4).xyz, vec3(0.0), vec3(2.0));
    float generatedRoughness = clamp(0.8, 0.0, 1.0);
    float generatedSpecular = clamp(0.1, 0.0, 2.0);
    float generatedEmissive = max(0.0, 0.0);
    return makeSample(generatedAlbedo, generatedRoughness, generatedSpecular, generatedEmissive);
