// Generated by VoxelParadox.ShaderEditor node graph.
// Edit via the ShaderEditor Node Graph panel; direct edits may be overwritten.
    vec3 n_0 = base;
    vec4 n_1 = blockTexel;
    vec3 n_2 = (n_0 * (n_1).xyz);
    vec3 stone_3_alb;
    float stone_3_rough;
    {
        vec2 sp = uv * (1.0);
        float strata = fbm21(vec2(sp.x * 3.4, sp.y * 1.4));
        float grain = simpleNoise2(localUv * 11.0);
        vec3 alb = (n_2) * mix(0.72, 1.15, strata);
        alb += vec3((grain - 0.5) * 0.06);
        stone_3_alb = clamp(alb, vec3(0.0), vec3(1.4));
        stone_3_rough = 0.92;
    }
    vec3 generatedAlbedo = clamp(stone_3_alb, vec3(0.0), vec3(2.0));
    float generatedRoughness = clamp(stone_3_rough, 0.0, 1.0);
    float generatedSpecular = clamp(0.1, 0.0, 2.0);
    float generatedEmissive = max(0.0, 0.0);
    return makeSample(generatedAlbedo, generatedRoughness, generatedSpecular, generatedEmissive);
