// Generated by VoxelParadox.ShaderEditor node graph.
// Edit via the ShaderEditor Node Graph panel; direct edits may be overwritten.
    vec3 n_0 = base;
    vec3 n_1 = blockColor;
    vec3 n_2 = (n_0 * n_1);
    vec3 generatedAlbedo = clamp(n_2, vec3(0.0), vec3(2.0));
    float generatedRoughness = clamp(0.8, 0.0, 1.0);
    float generatedSpecular = clamp(0.1, 0.0, 2.0);
    float generatedEmissive = max(0.0, 0.0);
    return makeSample(generatedAlbedo, generatedRoughness, generatedSpecular, generatedEmissive);
